### ISSUE TITLE
Error: useDeepCompareEffect should not be used with dependencies that are all primitive values

### ISSUE THREAD

**Issue by martinmorenoc** [nomadoda/react-media-devices#5]
It seems there is a bug using the hook in Next 13

```
Unhandled Runtime Error
Error: useDeepCompareEffect should not be used with dependencies that are all primitive values. Use React.useEffect instead.
```

I am just using the code of the readme

**Comment by Silas-Sitri** [comment]
watching, i seem to be getting the same error with next-js 14

**Comment by adamkrupke** [comment]
Fixed in 1.1.2

**Comment by sophie-pan** [comment]
The error remains

- node_modules/react-media-devices/lib/esm/useMediaDevices.js
<img width="853" alt="image" src="https://github.com/adamalfredsson/react-media-devices/assets/75846673/791579b1-dcc6-4e02-abf6-b06441837902">

- node_modules/react-media-devices/package.json
<img width="758" alt="image" src="https://github.com/adamalfredsson/react-media-devices/assets/75846673/d618357c-55e9-43fb-b680-fc4f61273328">

- package-lock.json
<img width="875" alt="image" src="https://github.com/adamalfredsson/react-media-devices/assets/75846673/aa0550bb-2169-48b9-8a54-a488685570c7">

**Comment by nerevarishe101** [comment]
same here

**Comment by adamkrupke** [comment]
Sorry about this, I failed to publish an updated build. I've added a github workflow to prevent this from occuring again. Please update to version 1.1.5.
